Repository mikiyasalehegn/Text-Analyzer, pull requests merged in 2023-06, with the labels that each got.

#2 Test1
  README.md
Labels: 1 min review

#4 Update README.md
  README.md
Labels: 1 min review, safe-change

#5 Update gitstream.cm
  .cm/gitstream.cm
Labels: cm-changes

#6 Update README.md
  README.md
Labels: 1 min review, safe-change

#7 Create welcome.cm
  .cm/welcome.cm
Labels: cm-changes

#8 test the new rule
  README.md
Labels: 1 min review, safe-change

#9 Create assignreviewbyde.cm
  .cm/assignreviewbyde.cm
Labels: cm-changes

#10 Update README.md
  README.md
Labels: 1 min review, safe-change

#12 Update assignreviewbyde.cm 2
  .cm/assignreviewbyde.cm
Labels: cm-changes

#11 Update README.md
  README.md
Labels: 1 min review, safe-change

#13 Update my.docs
  my.docs
Labels: 1 min review, safe-change

#15 Update assignreviewbyde.cm
  .cm/assignreviewbyde.cm
Labels: cm-changes

#14 Update my.docs
  my.docs
Labels: 1 min review, new-contributor

#16 Update my.docs
  my.docs
Labels: 1 min review

#17 Update my.docs
  my.docs
Labels: 1 min review

#18 Update my.docs
  my.docs
Labels: 1 min review

#19 Update my.docs
  my.docs
Labels: 1 min review

#20 Update my.docs
  my.docs
Labels: 1 min review

#32 Update mikk.txt
  src/app/auth/mikk.txt
Labels: 1 min review, safe-change

#33 Create assigncdexp.cm
  .cm/assigncdexp.cm
Labels: cm-changes

#35 mik.doc updated
  src/app/auth/mikk.txt
Labels: 1 min review, safe-change

#37 Update mikk.txt
  src/app/auth/mikk.txt
Labels: 1 min review, safe-change

#41 Update text analyzer.py 2
  text analyzer.py
Labels: 1 min review

#42 Update text analyzer.py 3
  text analyzer.py
Labels: 1 min review

#43 Create closepr.cm
  .cm/closepr.cm
Labels: cm-changes

#47 Try 2
  .cm/handlswimfiles.cm
Labels: cm-changes

#48 Create file2.swm
  file2.swm
Labels: 1 min review

#49 Update file2.swm
  file2.swm
Labels: 1 min review, safe-change

#50 Update file2.swm
  file2.swm
Labels: 1 min review

#51 Create swimming.swm
  .swm/swimming.swm
Labels: 1 min review, swimm-docs-only

#53 Try 2 jira
  .cm/checkjira.cm
Labels: cm-changes

#54 Update README.md
  README.md
Labels: 1 min review, safe-change, missing-jira

#55 Create mergedocs.cm
  .cm/mergedocs.cm
Labels: cm-changes

#56 Update my.docs
  my.docs
Labels: 1 min review, safe-change, missing-jira

#57 Update my.docs
  my.docs
Labels: 1 min review, missing-jira

#58 swimming.swm
  .swm/swimmingswm.vqy5ozuy.sw.md
Labels: 1 min review, safe-change, swimm-docs-only, missing-jira

#59 swimming.swm
  .swm/swimmingswm.g2hkqe0m.sw.md
Labels: 1 min review, safe-change, swimm-docs-only, missing-jira

#60 doc changed
  .swm/swimmingswm.g2hkqe0m.sw.md
  .swm/swimmingswm.vqy5ozuy.sw.md
  my.docs
Labels: 1 min review, missing-jira

#62 Update my.docs
  my.docs
Labels: 1 min review, safe-change, missing-jira

#64 Update my.docs
  my.docs
Labels: 1 min review, missing-jira

#66 Update text analyzer.py
  text analyzer.py
Labels: 1 min review, missing-jira

#65 Create requred_apvls.cm
  .cm/requred_apvls.cm
Labels: cm-changes

#74 Create updatelbls.cm
  .cm/updatelbls.cm
Labels: cm-changes

#75 Update README.md
  README.md
Labels: 1 min review, safe-change, missing-jira

#76 Update checking a quantity ingarients.py
  checking a quantity ingarients.py
Labels: missing-jira, 5 min review

#78 Create file2.txt
  file2.txt
Labels: 1 min review, safe-change, missing-jira

#81 Create specificrvr.cm
  .cm/specificrvr.cm
Labels: cm-changes

#83 Update ene.txt
  miko/ui/ene.txt
Labels: 1 min review, safe-change, missing-jira

#84 Update ene.txt
  miko/ui/ene.txt
Labels: 1 min review, safe-change, missing-jira

#85 Update ene.txt
  miko/ui/ene.txt
Labels: 1 min review, safe-change, missing-jira

#86 Update ene.txt
  miko/ui/ene.txt
Labels: 1 min review, safe-change, missing-jira

#88 Create first.js
  miko/ui/first.js
Labels: missing-jira, 10 min review

#89 Update specificrvr.cm
  .cm/specificrvr.cm
Labels: cm-changes

#90 Update ene.txt
  miko/ui/ene.txt
Labels: 1 min review, safe-change, missing-jira

#92 Update README.md
  README.md
Labels: 1 min review, safe-change, missing-jira
